# Generated by Django 5.1.1 on 2024-10-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('text', models.TextField()),
                ('prompt', models.TextField()),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
    ]
