# Generated by Django 5.1.1 on 2024-10-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
